
from dotenv import load_dotenv
import os

from google.adk.agents.llm_agent import LlmAgent
from google.adk.models.lite_llm import LiteLlm
from google.adk.agents.sequential_agent import SequentialAgent

from .instruction import (
    code_writer_instruction,
    code_writer_description,
    code_reviewer_instruction,
    code_reviewer_description,
    code_refactorer_instruction,
    code_refactorer_description,
)
# --- 1. Define Sub-Agents for Each Pipeline Stage ---

load_dotenv(override=True)

LLM_MODEL_NAME = os.getenv("LLM_MODEL_NAME")

# Code Writer Agent
# Takes the initial specification (from user query) and writes code.
code_writer_agent = LlmAgent(
    name="CodeWriterAgent",
    model=LiteLlm(model=LLM_MODEL_NAME),
    # Change 3: Improved instruction
    instruction=code_writer_instruction,
    description=code_writer_description,
    output_key="generated_code" # Stores output in state['generated_code']
)

# Code Reviewer Agent
# Takes the code generated by the previous agent (read from state) and provides feedback.
code_reviewer_agent = LlmAgent(
    name="CodeReviewerAgent",
    model=LiteLlm(model=LLM_MODEL_NAME),
    # Change 3: Improved instruction, correctly using state key injection
    instruction=code_reviewer_instruction,
    description=code_reviewer_description,
    output_key="review_comments", # Stores output in state['review_comments']
)


# Code Refactorer Agent
# Takes the original code and the review comments (read from state) and refactors the code.
code_refactorer_agent = LlmAgent(
    name="CodeRefactorerAgent",
    model=LiteLlm(model=LLM_MODEL_NAME),
    # Change 3: Improved instruction, correctly using state key injection
    instruction=code_refactorer_instruction,
    description=code_refactorer_description,
    output_key="refactored_code", # Stores output in state['refactored_code']
)


# --- 2. Create the SequentialAgent ---
# This agent orchestrates the pipeline by running the sub_agents in order.
code_pipeline_agent = SequentialAgent(
    name="CodePipelineAgent",
    sub_agents=[code_writer_agent, code_reviewer_agent, code_refactorer_agent],
    description="Executes a sequence of code writing, reviewing, and refactoring.",
    # The agents will run in the order provided: Writer -> Reviewer -> Refactorer
)

# For ADK tools compatibility, the root agent must be named `root_agent`
root_agent = code_pipeline_agent